# Generated by Django 2.0.7 on 2018-07-31 10:24

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180628_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
