# Generated by Django 2.0.7 on 2018-07-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180731_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.TextField(default='extraction goes here'),
            preserve_default=False,
        ),
    ]
